/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.MovingEndpointAssembly
import FirstPassageLinearTransport.MovingLowDensity
import FirstPassageLinearTransport.MovingTimeSupport
import FirstPassageLinearTransport.MovingFirstBad
import FirstPassageLinearTransport.MovingProfile
import FirstPassageLinearTransport.MovingSharpProfile

/-!
# Moving-endpoint formalization axiom audit

This module audits the internal V3.1 moving-endpoint producer, the moving
feasible-time support, the first-bad transport/profile adapter, and the
exact-rate sharp `q^{-1/2}` profile.  The public moving headline is not yet
exposed in `Main.lean`; uniform moving-stage startup, the eventual shell
producer, and the public assembly remain separate cut vertices.
-/

#print axioms FirstPassageLinearTransport.exists_barrierHitCount_real_normalized_le_binaryBarrierRate
#print axioms FirstPassageLinearTransport.exists_eventually_movingLowEntropyRate_ge_sub_div
#print axioms FirstPassageLinearTransport.exists_eventually_card_landingBad_movingLow_endpointRate_le
#print axioms FirstPassageLinearTransport.MovingRecertificationRun.directFirstPassage
#print axioms FirstPassageLinearTransport.MovingRecertificationRun.certified_endpoint_shell_eq
#print axioms FirstPassageLinearTransport.MovingRecertificationRun.deviation_add_potential_le
#print axioms FirstPassageLinearTransport.movingFeasibleTimes_card_le_potential
#print axioms FirstPassageLinearTransport.eventually_movingFeasibleTimes_card_lt_sqrt
#print axioms FirstPassageLinearTransport.eventually_nonempty_movingLowStageSetup
#print axioms FirstPassageLinearTransport.MovingRecertificationRun.toCertifiedRankChain
#print axioms FirstPassageLinearTransport.MovingRecertificationRun.scaledReverseLoss_le
#print axioms FirstPassageLinearTransport.movingFirstBadSourcesAtRank_subset_transport
#print axioms FirstPassageLinearTransport.movingFirstBadSourcesAtRank_card_le
#print axioms FirstPassageLinearTransport.movingFirstBadSourcesAtRank_density_le
#print axioms FirstPassageLinearTransport.movingSeparatedFailureEnvelope_density_terminalProfile
#print axioms FirstPassageLinearTransport.exists_exact_sharp_critical_low_series_bound
#print axioms FirstPassageLinearTransport.moving_low_firstBad_sharp_exact_sum_le
#print axioms FirstPassageLinearTransport.naturalDensityOne_of_movingShellError
#print axioms FirstPassageLinearTransport.movingEndpointNaturalDensityAssembly
