/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.ShrinkingParameters
import FirstPassageLinearTransport.VaryingDensity

/-!
# Scalar schedules for the moving polylogarithmic endpoint

This module formalizes the integer terminal rank and the critical entropy
buffer used by a shell-dependent exponent profile.  It contains no Collatz
transport estimate: the moving low-barrier density theorem is a separate
analytic input that must be proved before the public headline is assembled.
-/

namespace FirstPassageLinearTransport

open Filter
open scoped Real Topology

noncomputable section

/-- The entropy gap \(1-H_2(\log_3 2)\) in base two. -/
def firstPassageEntropyGap : ℝ :=
  1 - binaryEntropyBaseTwo logThreeTwo

theorem firstPassageEntropyGap_pos : 0 < firstPassageEntropyGap := by
  have hcritical := timeSupportCriticalExponent_pos
  rw [timeSupportCriticalExponent_eq_entropy] at hcritical
  unfold firstPassageEntropyGap
  by_contra h
  have hnonpos : 1 - binaryEntropyBaseTwo logThreeTwo ≤ 0 := le_of_not_gt h
  rcases hnonpos.eq_or_lt with hzero | hneg
  · rw [hzero] at hcritical
    norm_num at hcritical
  · have hden : 2 * (1 - binaryEntropyBaseTwo logThreeTwo) < 0 := by linarith
    have hfrac : 1 / (2 * (1 - binaryEntropyBaseTwo logThreeTwo)) < 0 := by
      exact one_div_neg.mpr hden
    linarith

theorem timeSupportCriticalExponent_mul_entropyGap :
    timeSupportCriticalExponent * firstPassageEntropyGap = 1 / 2 := by
  rw [timeSupportCriticalExponent_eq_entropy]
  change 1 / (2 * firstPassageEntropyGap) * firstPassageEntropyGap = 1 / 2
  field_simp [ne_of_gt firstPassageEntropyGap_pos]
  ring

/-- Integer terminal rank associated with a shell-dependent exponent. -/
def movingTerminalRank (A : ℕ → ℝ) (M : ℕ) : ℕ :=
  ⌈A M * Real.logb 2 ((M : ℝ) + 2)⌉₊

theorem movingTerminalRank_lower (A : ℕ → ℝ) (M : ℕ) :
    A M * Real.logb 2 ((M : ℝ) + 2) ≤
      (movingTerminalRank A M : ℝ) := by
  exact Nat.le_ceil _

theorem movingTerminalRank_lt_add_one
    {A : ℕ → ℝ} {M : ℕ} (hA : 0 ≤ A M) :
    (movingTerminalRank A M : ℝ) <
      A M * Real.logb 2 ((M : ℝ) + 2) + 1 := by
  apply Nat.ceil_lt_add_one
  have hx : (1 : ℝ) ≤ (M : ℝ) + 2 := by
    have hM : (0 : ℝ) ≤ M := Nat.cast_nonneg M
    linarith
  exact mul_nonneg hA (Real.logb_nonneg (by norm_num) hx)

/-- The terminal-rank ceiling costs only a factor two, pointwise in the
moving exponent. -/
theorem two_pow_movingTerminalRank_lt
    {A : ℕ → ℝ} {M : ℕ} (hA : 0 ≤ A M) :
    ((2 ^ movingTerminalRank A M : ℕ) : ℝ) <
      2 * (((M : ℝ) + 2) ^ (A M)) := by
  have hx : 0 < (M : ℝ) + 2 := by positivity
  have hExp := movingTerminalRank_lt_add_one hA
  rw [Nat.cast_pow, ← Real.rpow_natCast]
  calc
    (2 : ℝ) ^ (movingTerminalRank A M : ℝ) <
        (2 : ℝ) ^ (A M * Real.logb 2 ((M : ℝ) + 2) + 1) :=
      Real.rpow_lt_rpow_of_exponent_lt (by norm_num) hExp
    _ = 2 * (((M : ℝ) + 2) ^ (A M)) := by
      rw [Real.rpow_add (by norm_num), Real.rpow_one]
      rw [show A M * Real.logb 2 ((M : ℝ) + 2) =
          Real.logb 2 ((M : ℝ) + 2) * A M by ring]
      rw [Real.rpow_mul (by norm_num),
        Real.rpow_logb (by norm_num) (by norm_num) hx]
      ring

/-- Critical buffer attached directly to an integer terminal-rank schedule. -/
def criticalRankBuffer (L : ℕ → ℕ) (M : ℕ) : ℝ :=
  firstPassageEntropyGap * L M -
    (1 / 2) * Real.logb 2 ((M : ℝ) + 2) -
    Real.logb 2 (Real.log ((M : ℝ) + 3))

/-- Critical buffer for the rank generated by a moving exponent profile. -/
def movingRankBuffer (A : ℕ → ℝ) (M : ℕ) : ℝ :=
  criticalRankBuffer (movingTerminalRank A) M

theorem movingRankBuffer_eq (A : ℕ → ℝ) (M : ℕ) :
    movingRankBuffer A M =
      firstPassageEntropyGap * movingTerminalRank A M -
        (1 / 2) * Real.logb 2 ((M : ℝ) + 2) -
        Real.logb 2 (Real.log ((M : ℝ) + 3)) := rfl

/-- The two terms in the shell bound vanish when the critical buffer tends to
infinity and the high-rank exponent is positive. -/
theorem tendsto_movingShellError_zero
    {A : ℕ → ℝ} {eps : ℝ}
    (hbuffer : Tendsto (movingRankBuffer A) atTop atTop)
    (heps : 0 < eps) :
    Tendsto
      (fun M : ℕ =>
        (2 : ℝ) ^ (-(movingRankBuffer A M)) +
          (((M : ℝ) + 2) ^ (-eps)))
      atTop (nhds 0) := by
  have htwo : (1 : ℝ) < 2 := by norm_num
  have hnegBuffer : Tendsto (fun M : ℕ => -(movingRankBuffer A M)) atTop atBot :=
    tendsto_neg_atBot_iff.mpr hbuffer
  have hfirst : Tendsto (fun M : ℕ => (2 : ℝ) ^ (-(movingRankBuffer A M)))
      atTop (nhds 0) := by
    simpa only using
      (tendsto_rpow_atBot_of_base_gt_one (2 : ℝ) htwo).comp hnegBuffer
  have hxT : Tendsto (fun M : ℕ => (M : ℝ) + 2) atTop atTop :=
    tendsto_atTop_add_const_right atTop (2 : ℝ) tendsto_natCast_atTop_atTop
  have hsecond : Tendsto (fun M : ℕ => ((M : ℝ) + 2) ^ (-eps))
      atTop (nhds 0) := by
    simpa only using (tendsto_rpow_neg_atTop heps).comp hxT
  simpa using hfirst.add hsecond

/-- A shell family with the moving endpoint error profile assembles to a
natural-density-one set. -/
theorem naturalDensityOne_of_movingShellError
    (S : ℕ → Set ℕ) {A : ℕ → ℝ} {C eps : ℝ}
    (heps : 0 < eps)
    (hbuffer : Tendsto (movingRankBuffer A) atTop atTop)
    (hShell : ∀ᶠ M : ℕ in atTop,
      shellExceptionalRatio (S M) M ≤
        C * ((2 : ℝ) ^ (-(movingRankBuffer A M)) +
          (((M : ℝ) + 2) ^ (-eps)))) :
    NaturalDensityOne (assembleDyadic S) := by
  apply naturalDensityOne_assembleDyadic S
  apply squeeze_zero'
  · exact Eventually.of_forall fun M => shellExceptionalRatio_nonneg (S M) M
  · exact hShell
  · have hconst : Tendsto (fun _ : ℕ => C) atTop (nhds C) := tendsto_const_nhds
    simpa using hconst.mul (tendsto_movingShellError_zero hbuffer heps)

end

end FirstPassageLinearTransport
