/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.Main
import FirstPassageLinearTransport.PaperDependencyAudit

/-!
# First-passage manuscript axiom audit

Public `#print axioms` surface for the standalone V3 manuscript. This module
reports logical trust; `PaperDependencyAudit` separately reports declaration
and source-elaboration reachability, while a full `lake build` remains the
source-reconstruction gate.
-/

-- Parity coding and the exact affine iterate.
#print axioms FirstPassageLinearTransport.naturalDensityOne_assembleDyadic
#print axioms
  FirstPassageLinearTransport.QuantitativeDensity.badCount_assembleDyadic_le_stretched_log
#print axioms FirstPassageLinearTransport.parityCode_bijective
#print axioms FirstPassageLinearTransport.exact_affine_iterate

-- Maximal barrier and dense initial window.
#print axioms FirstPassageLinearTransport.barrierHitCount_le_exp
#print axioms FirstPassageLinearTransport.card_shellMaximalParityBad_le
#print axioms FirstPassageLinearTransport.orbit_envelope_of_maximalBarrier
#print axioms FirstPassageLinearTransport.initialWindowGood_powerDense
#print axioms FirstPassageLinearTransport.extendedWindow_powerDense

-- First-passage reversal and loss-filtered transport.
#print axioms FirstPassageLinearTransport.firstPassage_band
#print axioms FirstPassageLinearTransport.reverse_product_identity
#print axioms FirstPassageLinearTransport.firstPassage_reverse_bounds
#print axioms FirstPassageLinearTransport.lossFiltered_oddCount_rigidity
#print axioms FirstPassageLinearTransport.lossFilteredTaggedFiber_bound
#print axioms FirstPassageLinearTransport.lossFiltered_arbitraryTarget_transport
#print axioms FirstPassageLinearTransport.lossFiltered_arbitraryTarget_transport_restricted

-- Nested direct re-certification and rank-scaled loss.
#print axioms FirstPassageLinearTransport.CertifiedRankChain.directFirstPassage
#print axioms FirstPassageLinearTransport.RecertificationRun.toCertifiedRankChain
#print axioms FirstPassageLinearTransport.scaledReverseLoss_add_rescaled
#print axioms FirstPassageLinearTransport.CertifiedRankChain.scaledReverseLoss_le
#print axioms FirstPassageLinearTransport.RecertificationRun.toGeneratedFirstBadLanding
#print axioms FirstPassageLinearTransport.generatedFirstBadSources_density_terminalProfile

-- Shrinking barriers and support-sensitive aggregation.
#print axioms FirstPassageLinearTransport.certified_firstPassage_duration_corridor
#print axioms FirstPassageLinearTransport.shrinkingFeasibleTimes_card_lt_sqrt
#print axioms FirstPassageLinearTransport.shrinkingSeparatedFailureEnvelope_density_terminalProfile
#print axioms FirstPassageLinearTransport.eventually_shrinkingFailureEnvelope_density_polylog_le
#print axioms FirstPassageLinearTransport.exists_stageSetup

-- Optimized fixed-polylogarithmic assembly and literal referee-facing theorem.
#print axioms FirstPassageLinearTransport.timeSupportCriticalExponent_eq_entropy
#print axioms FirstPassageLinearTransport.lossFiltered_arbitraryTarget_transport_atTimes_uniform
#print axioms FirstPassageLinearTransport.ShrinkingRecertificationRun.directFirstPassage
#print axioms FirstPassageLinearTransport.ShrinkingRecertificationRun.elapsed_le_horizon
#print axioms FirstPassageLinearTransport.shrinkingFeasibleTimes_card_lt_sqrt
#print axioms FirstPassageLinearTransport.card_shellInitialWindowBad_shrinking_le
#print axioms FirstPassageLinearTransport.shrinkingFirstBadSourcesAtRank_card_le
#print axioms FirstPassageLinearTransport.shrinkingSeparatedFailureEnvelope_density_terminalProfile
#print axioms FirstPassageLinearTransport.eventually_sqrtSupport_mul_terminalTail_polylog_le_power
#print axioms FirstPassageLinearTransport.eventually_shrinkingFailureEnvelope_density_polylog_le
#print axioms FirstPassageLinearTransport.exists_shrinkingPolylogParameterPackage
#print axioms FirstPassageLinearTransport.shrinkingRun_terminal_or_firstBad
#print axioms FirstPassageLinearTransport.ShrinkingRecertificationRun.orbit_le_start_power
#print axioms FirstPassageLinearTransport.shrinkingFixedPolylogNaturalDensityDescent
#print axioms FirstPassageLinearTransport.fixedPolylogCriticalExponent_eq_entropy
#print axioms FirstPassageLinearTransport.fixedPolylogClockCritical_eq_paper
#print axioms FirstPassageLinearTransport.exists_fixedPolylogParameterPackage
#print axioms FirstPassageLinearTransport.fixedPolylogNaturalDensityLanding
#print axioms FirstPassageLinearTransport.TwoRegimeRecertificationRun.orbit_le_start_power
#print axioms FirstPassageLinearTransport.fixedPolylogNaturalDensityDescent
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_fixed_polylogarithmic_natural_density_descent

-- Quantitative companions retained in the streamlined manuscript.
#print axioms FirstPassageLinearTransport.stageLength_le_heightSensitiveHorizon
#print axioms FirstPassageLinearTransport.rawOrbit_rawTime_eq_orbit
#print axioms FirstPassageLinearTransport.eventuallyShellRawClockLt
#print axioms FirstPassageLinearTransport.firstPassageLinearTransportRawMain
#print axioms FirstPassageLinearTransport.firstPassageLinearTransportQuantitativeStretched
#print axioms FirstPassageLinearTransport.firstPassageLinearTransportQuantitativeFixedPower
#print axioms FirstPassageLinearTransport.orbit_le_stageClock_ceiling
#print axioms FirstPassageLinearTransport.eventuallyShellOrbitCeiling
#print axioms FirstPassageLinearTransport.firstPassageLinearTransportOrbitCeiling
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_stretched_log_natural_density_descent
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_stretched_log_natural_density_descent_unclocked
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_fixed_power_natural_density_descent
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_quantitative_stretched_exceptional_count
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_raw_stretched_log_natural_density_descent
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_stretched_log_descent_with_orbit_ceiling
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_quantitative_fixed_power_exceptional_count
#print axioms FirstPassageLinearTransport.bootstrapSet_powerDense
#print axioms FirstPassageLinearTransport.stageClock_le_heightClock
#print axioms FirstPassageLinearTransport.exists_gradedClockParameters
#print axioms FirstPassageLinearTransport.firstPassageLinearTransportGradedPower
#print axioms
  FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_graded_power_natural_density_descent
