/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.Main
import FirstPassageLinearTransport.Legacy

import FirstPassageLinearTransport.Extras.Unreachable
/-!
# Historical fixed-exponent V3 cut-vertex axiom audit

This retained audit prints the trusted axioms of the fixed-exponent V3 chain.
It does not claim coverage of the later moving/timeout headline.  The canonical
route is audited by `TimeoutEndpointAudit`; the optional historical comparison
is audited separately by `Alternates.AllPrefix.Audit`.
-/

#print axioms FirstPassageLinearTransport.lossFiltered_arbitraryTarget_transport_uniform
#print axioms FirstPassageLinearTransport.IsFirstPassage.nested
#print axioms FirstPassageLinearTransport.CertifiedRankChain.directFirstPassage
#print axioms FirstPassageLinearTransport.CertifiedRankChain.scaledReverseLoss_le
#print axioms FirstPassageLinearTransport.barrierHitCount_le_binaryEntropy
#print axioms FirstPassageLinearTransport.orbit_envelope_of_adjustableBarrier
#print axioms FirstPassageLinearTransport.eventually_card_shellInitialWindowBad_adjustable_le
#print axioms FirstPassageLinearTransport.generatedFirstBadSources_subset_envelope
#print axioms FirstPassageLinearTransport.generatedFirstBadSources_card_le
#print axioms FirstPassageLinearTransport.parentRank_le_rationalTargetBudget
#print axioms FirstPassageLinearTransport.CertifiedRankChain.first_of_stage
#print axioms FirstPassageLinearTransport.CertifiedRankChain.next_of_stage
#print axioms FirstPassageLinearTransport.RecertificationRun.toCertifiedRankChain
#print axioms FirstPassageLinearTransport.RecertificationRun.endpoint_mem_landingBad
#print axioms FirstPassageLinearTransport.RecertificationRun.toGeneratedFirstBadLanding
#print axioms FirstPassageLinearTransport.weighted_exp_Icc_le
#print axioms FirstPassageLinearTransport.generatedFirstBadSources_density_terminalProfile
#print axioms FirstPassageLinearTransport.eventually_interval_card_landingBad_adjustable_le
#print axioms FirstPassageLinearTransport.parentRank_le_commonTargetBudget
#print axioms FirstPassageLinearTransport.MixedRecertificationRun.toCertifiedRankChain
#print axioms FirstPassageLinearTransport.twoRegimeFailureSources_subset_envelope
#print axioms FirstPassageLinearTransport.twoRegimeFailureEnvelope_density_terminalProfile
#print axioms FirstPassageLinearTransport.TwoRegimeRecertificationRun.directFirstPassage
#print axioms FirstPassageLinearTransport.TwoRegimeRecertificationRun.elapsed_le_horizon
#print axioms FirstPassageLinearTransport.twoRegimeRun_terminal_or_firstBad
#print axioms FirstPassageLinearTransport.twoRegimeSource_lands_below_horizon
#print axioms FirstPassageLinearTransport.eventually_polylogSwitchRank_lt_source
#print axioms FirstPassageLinearTransport.eventually_polylogTerminalRank_lt_switchRank
#print axioms FirstPassageLinearTransport.eventually_twoRegimeHorizon_lt_shellClock
#print axioms FirstPassageLinearTransport.eventually_interval_rankTransport_small
#print axioms FirstPassageLinearTransport.eventually_initialEntropyTail_le_power
#print axioms FirstPassageLinearTransport.eventually_canonicalTwoRegimeTailProfile_le_power
#print axioms FirstPassageLinearTransport.eventually_twoRegimeFailureEnvelope_density_polylog_le
#print axioms FirstPassageLinearTransport.eventually_twoRegimeFailureSources_density_polylog_le
#print axioms FirstPassageLinearTransport.naturalDensityOne_twoRegimePolylogGood
#print axioms FirstPassageLinearTransport.eventually_badCount_assembleDyadic_le_polylog_profile
#print axioms FirstPassageLinearTransport.eventually_badCount_twoRegimePolylogGood_le
#print axioms FirstPassageLinearTransport.eventually_halfNatLog_profile_le_natLog
#print axioms FirstPassageLinearTransport.eventually_badCount_assembleDyadic_le_natLog_profile
#print axioms FirstPassageLinearTransport.eventually_badCount_twoRegimePolylogGood_le_natLog
#print axioms FirstPassageLinearTransport.fixedPolylogCriticalExponent_eq_entropy
#print axioms FirstPassageLinearTransport.fixedPolylogClockCritical_eq_paper
#print axioms FirstPassageLinearTransport.exists_lowBarrier_rate_margin_of_critical_lt
#print axioms FirstPassageLinearTransport.exists_fixedPolylogParameterPackage
#print axioms FirstPassageLinearTransport.two_pow_polylogTerminalRank_lt
#print axioms FirstPassageLinearTransport.eventually_twoRegimePolylogGood_has_shellLanding
#print axioms FirstPassageLinearTransport.fixedPolylogNaturalDensityLanding
#print axioms FirstPassageLinearTransport.TwoRegimeRecertificationRun.currentRank_lt_startShell
#print axioms FirstPassageLinearTransport.TwoRegimeRecertificationRun.orbit_le_start_power
#print axioms FirstPassageLinearTransport.eventually_twoRegimePolylogGood_has_shellLanding_with_orbitCeiling
#print axioms FirstPassageLinearTransport.fixedPolylogNaturalDensityDescent
#print axioms FirstPassageLinearTransport.timeSupportCriticalExponent_eq_entropy
#print axioms FirstPassageLinearTransport.lossFiltered_arbitraryTarget_transport_atTimes_uniform
#print axioms FirstPassageLinearTransport.ShrinkingRecertificationRun.certified_endpoint_shell_eq
#print axioms FirstPassageLinearTransport.shrinkingFeasibleTimes_card_lt_sqrt
#print axioms FirstPassageLinearTransport.shrinkingFirstBadSourcesAtRank_subset_transport
#print axioms FirstPassageLinearTransport.shrinkingSeparatedFailureEnvelope_density_terminalProfile
#print axioms FirstPassageLinearTransport.eventually_sqrt_mul_log_rpow_le
#print axioms FirstPassageLinearTransport.eventually_shrinkingPolylogTerminalProfile_le_power
#print axioms FirstPassageLinearTransport.exists_shrinkingPolylogParameterPackage
#print axioms FirstPassageLinearTransport.shrinkingSource_terminal_or_failure
#print axioms FirstPassageLinearTransport.eventually_shrinkingPolylogGood_has_shellLanding_with_orbitCeiling
#print axioms FirstPassageLinearTransport.shrinkingFixedPolylogNaturalDensityDescent
#print axioms FirstPassageLinearTransport.QuantitativeCollatzMain.collatz_first_passage_fixed_polylogarithmic_natural_density_descent
