/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.MovingLowParameters

import FirstPassageLinearTransport.Extras.Unreachable
/-!
# Moving low-rank parameters for the optional all-prefix route

This module contains the displacement and entropy-rate refinements used only
by the all-prefix alternate proof.  The canonical timeout library retains the
shared moving parameter limits, but does not import this optional layer.
-/

namespace FirstPassageLinearTransport

open Filter
open scoped Real Topology

noncomputable section

/-- Boolean displacement generated by the moving low parameters. -/
def movingLowDisplacement (K₀ K₁ : ℝ) (L : ℕ) : ℝ :=
  adjustableBarrierDisplacement
    (movingLowLambda K₁ L) (movingLowTolerance K₀ L)

/-- Entropy rate generated by the moving low parameters. -/
def movingLowEntropyRate (K₀ K₁ : ℝ) (L : ℕ) : ℝ :=
  binaryBarrierRate (movingLowDisplacement K₀ K₁ L)

/-- The threshold ratio exceeds `a₀ + η_L` by exactly `K₀/(2L)`. -/
theorem movingLow_passageMargin (K₀ : ℝ) (L : ℕ) :
    movingLowRatio K₀ L - a0 - movingLowTolerance K₀ L =
      K₀ / (2 * (L : ℝ)) := by
  unfold movingLowRatio movingLowTolerance driftGap
  ring

/-- Exact unused multiplicative margin in the adjustable envelope. -/
theorem movingLow_multiplicativeMargin (K₀ K₁ : ℝ) (L m : ℕ) :
    (1 - movingLowLambda K₁ L) * movingLowTolerance K₀ L * (m : ℝ) =
      K₁ * movingLowTolerance K₀ L * ((m : ℝ) / (L : ℝ)) := by
  unfold movingLowLambda
  ring

/-- Every low parent rank `m ≥ L` retains the fixed passage margin `K₀/2`. -/
theorem movingLow_passageMargin_mul_parent
    {K₀ : ℝ} {L m : ℕ} (hK₀ : 0 ≤ K₀) (hL : 0 < L) (hLm : L ≤ m) :
    K₀ / 2 ≤
      (movingLowRatio K₀ L - a0 - movingLowTolerance K₀ L) * (m : ℝ) := by
  rw [movingLow_passageMargin]
  have hLR : 0 < (L : ℝ) := by positivity
  have hmL : 1 ≤ (m : ℝ) / (L : ℝ) := by
    rw [le_div_iff₀ hLR]
    have hLmR : (L : ℝ) ≤ (m : ℝ) := by exact_mod_cast hLm
    simpa using hLmR
  have hKhalf : 0 ≤ K₀ / 2 :=
    div_nonneg hK₀ (by norm_num : (0 : ℝ) ≤ 2)
  calc
    K₀ / 2 ≤ (K₀ / 2) * ((m : ℝ) / (L : ℝ)) :=
      by simpa using mul_le_mul_of_nonneg_left hmL hKhalf
    _ = K₀ / (2 * (L : ℝ)) * (m : ℝ) := by
      field_simp [hLR.ne']

/-- Every low parent rank `m ≥ L` also retains the fixed unused
multiplicative margin `K₁ η_L`. -/
theorem movingLow_multiplicativeMargin_mul_parent
    {K₀ K₁ : ℝ} {L m : ℕ}
    (hK₁ : 0 ≤ K₁) (hL : 0 < L) (hLm : L ≤ m)
    (hTolerance : 0 ≤ movingLowTolerance K₀ L) :
    K₁ * movingLowTolerance K₀ L ≤
      (1 - movingLowLambda K₁ L) * movingLowTolerance K₀ L * (m : ℝ) := by
  rw [movingLow_multiplicativeMargin]
  have hLR : 0 < (L : ℝ) := by positivity
  have hmL : 1 ≤ (m : ℝ) / (L : ℝ) := by
    rw [le_div_iff₀ hLR]
    have hLmR : (L : ℝ) ≤ (m : ℝ) := by exact_mod_cast hLm
    simpa using hLmR
  exact le_mul_of_one_le_right (mul_nonneg hK₁ hTolerance) hmL

/-- Exact first-order displacement error.  This identity is the algebraic
source of the `O(1/L)` entropy-rate loss. -/
theorem movingLowDisplacement_error_eq
    (K₀ K₁ : ℝ) (L : ℕ) :
    firstPassageEndpointDisplacement - movingLowDisplacement K₀ K₁ L =
      (((K₀ + K₁ * driftGap) / (L : ℝ) -
          K₀ * K₁ / (L : ℝ) ^ 2) / logTwoThree) := by
  unfold firstPassageEndpointDisplacement movingLowDisplacement
    adjustableBarrierDisplacement movingLowLambda movingLowTolerance
  ring

/-- A one-sided `O(1/L)` displacement estimate sufficient for the later
Lipschitz rate comparison. -/
theorem movingLowDisplacement_error_le
    {K₀ K₁ : ℝ} {L : ℕ}
    (hK₀ : 0 ≤ K₀) (hK₁ : 0 ≤ K₁) (hL : 0 < L) :
    firstPassageEndpointDisplacement - movingLowDisplacement K₀ K₁ L ≤
      (K₀ + K₁ * driftGap) /
        ((L : ℝ) * logTwoThree) := by
  rw [movingLowDisplacement_error_eq]
  have hLR : 0 < (L : ℝ) := by positivity
  have hterm : 0 ≤ K₀ * K₁ / (L : ℝ) ^ 2 := by positivity
  have hinner :
      (K₀ + K₁ * driftGap) / (L : ℝ) - K₀ * K₁ / (L : ℝ) ^ 2 ≤
        (K₀ + K₁ * driftGap) / (L : ℝ) := by linarith
  calc
    ((K₀ + K₁ * driftGap) / (L : ℝ) -
        K₀ * K₁ / (L : ℝ) ^ 2) / logTwoThree ≤
      ((K₀ + K₁ * driftGap) / (L : ℝ)) / logTwoThree :=
        (div_le_div_iff_of_pos_right logTwoThree_pos).2 hinner
    _ = (K₀ + K₁ * driftGap) /
        ((L : ℝ) * logTwoThree) := by ring

theorem tendsto_movingLowDisplacement (K₀ K₁ : ℝ) :
    Tendsto (movingLowDisplacement K₀ K₁)
      atTop (nhds firstPassageEndpointDisplacement) := by
  have hmul := (tendsto_movingLowLambda K₁).mul
    (tendsto_movingLowTolerance K₀)
  simpa [movingLowDisplacement, adjustableBarrierDisplacement,
    firstPassageEndpointDisplacement] using hmul.div_const logTwoThree

theorem tendsto_movingLowEntropyRate (K₀ K₁ : ℝ) :
    Tendsto (movingLowEntropyRate K₀ K₁)
      atTop (nhds firstPassageEndpointRate) := by
  unfold movingLowEntropyRate firstPassageEndpointRate
  exact continuous_binaryBarrierRate.continuousAt.tendsto.comp
    (tendsto_movingLowDisplacement K₀ K₁)

/-- Quantitative endpoint approach for the entropy rate.  This is the formal
`b_L ≥ b_* - C/L` estimate used by the optional all-prefix route. -/
theorem exists_eventually_movingLowEntropyRate_ge_sub_div
    {K₀ K₁ : ℝ} (hK₀ : 0 < K₀) (hK₁ : 0 < K₁) :
    ∃ C : ℝ, 0 < C ∧
      ∀ᶠ L : ℕ in atTop,
        firstPassageEndpointRate - C / (L : ℝ) ≤
          movingLowEntropyRate K₀ K₁ L := by
  obtain ⟨C₀, hC₀, hLip⟩ := exists_binaryBarrierRate_endpoint_lipschitz
  let D := (K₀ + K₁ * driftGap) / logTwoThree
  have hD : 0 < D := by
    dsimp [D]
    exact div_pos (add_pos hK₀ (mul_pos hK₁ driftGap_pos)) logTwoThree_pos
  refine ⟨C₀ * D, mul_pos hC₀ hD, ?_⟩
  have hhalfLt :
      firstPassageEndpointDisplacement / 2 <
        firstPassageEndpointDisplacement := by
    linarith [firstPassageEndpointDisplacement_pos]
  have hLower := (tendsto_movingLowDisplacement K₀ K₁).eventually
    (Ioi_mem_nhds hhalfLt)
  have hAdm := eventually_movingLow_admissible hK₀ hK₁
  filter_upwards [hLower, hAdm, eventually_ge_atTop (1 : ℕ)]
    with L hLower hAdm hL
  have hLR : 0 < (L : ℝ) := by positivity
  have hDispUpper :
      movingLowDisplacement K₀ K₁ L ≤ firstPassageEndpointDisplacement := by
    unfold movingLowDisplacement adjustableBarrierDisplacement
      firstPassageEndpointDisplacement
    apply (div_le_div_iff_of_pos_right logTwoThree_pos).2
    have hmul :
        movingLowLambda K₁ L * movingLowTolerance K₀ L ≤
          movingLowTolerance K₀ L := by
      simpa using mul_le_mul_of_nonneg_right hAdm.2.2.2.2.2.1.le hAdm.1.le
    exact hmul.trans hAdm.2.1.le
  have hEndpointWindow :
      firstPassageEndpointDisplacement ∈
        Set.Icc (firstPassageEndpointDisplacement / 2)
          firstPassageEndpointDisplacement :=
    ⟨hhalfLt.le, le_rfl⟩
  have hMovingWindow :
      movingLowDisplacement K₀ K₁ L ∈
        Set.Icc (firstPassageEndpointDisplacement / 2)
          firstPassageEndpointDisplacement :=
    ⟨hLower.le, hDispUpper⟩
  have hRateNorm := hLip
    (movingLowDisplacement K₀ K₁ L) hMovingWindow
    firstPassageEndpointDisplacement hEndpointWindow
  have hDispError := movingLowDisplacement_error_le
    hK₀.le hK₁.le hL
  have hDispNonneg :
      0 ≤ firstPassageEndpointDisplacement -
        movingLowDisplacement K₀ K₁ L := sub_nonneg.mpr hDispUpper
  have hRateError :
      firstPassageEndpointRate - movingLowEntropyRate K₀ K₁ L ≤
        C₀ * (firstPassageEndpointDisplacement -
          movingLowDisplacement K₀ K₁ L) := by
    calc
      firstPassageEndpointRate - movingLowEntropyRate K₀ K₁ L ≤
          ‖firstPassageEndpointRate - movingLowEntropyRate K₀ K₁ L‖ :=
        le_abs_self _
      _ ≤ C₀ * ‖firstPassageEndpointDisplacement -
          movingLowDisplacement K₀ K₁ L‖ := by
        simpa [firstPassageEndpointRate, movingLowEntropyRate] using hRateNorm
      _ = C₀ * (firstPassageEndpointDisplacement -
          movingLowDisplacement K₀ K₁ L) := by
        rw [Real.norm_eq_abs, abs_of_nonneg hDispNonneg]
  have hScaledError :
      C₀ * (firstPassageEndpointDisplacement -
          movingLowDisplacement K₀ K₁ L) ≤
        (C₀ * D) / (L : ℝ) := by
    have hmul := mul_le_mul_of_nonneg_left hDispError hC₀.le
    dsimp [D]
    calc
      C₀ * (firstPassageEndpointDisplacement -
          movingLowDisplacement K₀ K₁ L) ≤
        C₀ * ((K₀ + K₁ * driftGap) /
          ((L : ℝ) * logTwoThree)) := hmul
      _ = (C₀ * ((K₀ + K₁ * driftGap) / logTwoThree)) /
          (L : ℝ) := by ring
  linarith [hRateError.trans hScaledError]

end

end FirstPassageLinearTransport
